services:
  app:
    image: ghcr.io/pocket-id/pocket-id
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: "curl -f http://localhost:1411/healthz"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - app_data:/app/data
    networks:
      proxy_apps:

volumes:
  app_data:

networks:
  proxy_apps:
    name: proxy_apps
    external: true
